### ISSUE TITLE
Outdated instructions to use this library

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/go-app-sdk#11]
`vgo` has been superseded by `go 1.11` and commands have changed slightly.

These instructions seem to work;

-   create a folder somewhere outside `$GOPATH`
-   `go mod <your-module-name>`
-   put a main.go file in there, importing `github.com/TheThingsNetwork/go-app-sdk`
-   `go mod vendor`
-   `go run main.go`

What I doubt still is whether this is the way it is supposed to work. `go get github.com/TheThingsNetwork/go-app-sdk` fails with type compatibility issue with `lorawan` package.

**Comment by NeuralSpaz** [comment]
Modules are promising but still at an experimental feature stage, not sure its quite ready yet to jump on the band wagon. I would still recommend you tag this when you find a workable solution, so that it gives good info to go mod.

**Comment by johanstokking** [comment]
That's right, but the instructions already use modules and those instructions are outdated. Better to update them.

We had other instructions [before, using dep](https://github.com/TheThingsNetwork/go-app-sdk/commit/cc04392958e82a199efd758b734456f8e736617f), but they didn't work anymore due to a dependency conflict, so we stay with modules for now.

**Comment by NeuralSpaz** [comment]
Pretty much, both package and doc need some love. 
I'm not sure how much work would be required to pull it up to use head or even if they are even still compatible with the different versions of api/lorawan/protocol. It is particularly tricky to track where the break in compatibility is since most of the deps are not versioned and all the fun of the minor []byte changes to brocaar/lorawan thrown in for good measure too.
 
Maybe its too much for it to be go gettable without a rework. 

I have updated go.mod to be suitable for go1.11.4 there is some git weirdness with go.sum that will stop it from working. 

starting from a go.mod file like this 
```
module github.com/TheThingsNetwork/go-app-sdk

require (
	github.com/TheThingsNetwork/api v0.0.0-20180620113421-22ad17f21fd5
	github.com/TheThingsNetwork/go-account-lib v2.0.3+incompatible
	github.com/TheThingsNetwork/go-utils v0.0.0-20171120090236-94b302f97692
	github.com/TheThingsNetwork/ttn v2.9.4+incompatible
    	github.com/brocaar/lorawan v0.0.0-20170912083535-493811893ace // indirect	
)
```
with env GO111MODULE=on
running go mod tidy will go and grab all the things to make it work, but the contents of go.sum seems to be sensitive to the version of go you are using. I wondering if that should be empty.
Share and enjoy.

**Comment by NeuralSpaz** [comment]
seems like 
`github.com/brocaar/lorawan v0.0.0-20170912083535-493811893ace`
is the only one that really stand in the way of this being go gettable. All the rest seem to be able to pull from head and pass tests.

So one possible way is to for fork, freeze and update references in:
```
$go mod why github.com/brocaar/lorawan
# github.com/brocaar/lorawan
github.com/TheThingsNetwork/go-app-sdk
github.com/TheThingsNetwork/api/protocol/lorawan
github.com/brocaar/lorawan
```
there does not seem to many [imports](https://github.com/TheThingsNetwork/api/search?q=brocaar%2Florawan&unscoped_q=brocaar%2Florawan) of it in /api

**Comment by MarkStanley** [comment]
Hiya, I'm failing badly to use go-app-sdk - I get type errors.  Is it in a working state or should I come back later?

**Comment by NeuralSpaz** [comment]
Hi Mark, my open PR's have a work around to resolve the type errors and make it work. You could always use those commits(#10, #12). Hit me up if you need a hand with that.
The PR's have not been reviewed by @htdvisser from ttn yet. The outdated doc Issues were filed along with the PR's.

**Comment by MarkStanley** [comment]
Thanks @NeuralSpaz - I'd be happy to use your workaround for now - how can I do that?

**Comment by htdvisser** [comment]
We've been working very hard on our v3 stack (https://github.com/TheThingsNetwork/lorawan-stack), so this one went to the "later" pile. 

Ideally, we would switch the entire v2 stack over from a mix of `govendor` and `golang/dep` to Go 1.11 modules. Unfortunately the v2 code doesn't work very well with Go 1.11 modules. This is because of some nasty circular dependencies we introduced when splitting the `github.com/TheThingsNetwork/api` out of `github.com/TheThingsNetwork/ttn` (ttn imports api, which in turn imports types form ttn). 

I gave @NeuralSpaz's solution a quick look. The type aliases looks like a very reasonable way to clean up this mess, but I'm not so sure about the Go 1.9 build tags. I'll dive into this a bit more when I have the time. Perhaps we can combine these changes with a complete upgrade to Go 1.12 (when it's released).

**Comment by NeuralSpaz** [comment]
@MarkStanley here are is some quick instructions and example.
1. Pull my repo
`go get github.com/NeuralSpaz/go-app-sdk`
2. go into directory
`cd go-app-sdk`
3. Checkout "workaround" branch
`git checkout workaround`
4. Run dep (you may need to [install dep](https://github.com/golang/dep#installation)).
`dep ensure`
5. Use something like this: Use the your appID and api-keys.
```go
package main

import (
	"fmt"
	"os"

	ttnsdk "github.com/NeuralSpaz/go-app-sdk"
	ttnlog "github.com/TheThingsNetwork/go-utils/log"
	"github.com/TheThingsNetwork/go-utils/log/apex"
)

const (
	sdkClientName = "MY-APP-NAME"
	appID         = "APP_ID"
	appAccessKey  = "APP_API_KEY"
)

func main() {
	log := apex.Stdout() // We use a cli logger at Stdout
	log.MustParseLevel("debug")
	ttnlog.Set(log) // Set the logger as default for TTN

	if appID == "" || appAccessKey == "" {
		os.Exit(0)
	}
	config := ttnsdk.NewCommunityConfig(sdkClientName)
	config.ClientVersion = "2.0.5" // The version of the application

	// Create a new SDK client for the application
	client := config.NewClient(appID, appAccessKey)

	// Make sure the client is closed before the function returns
	// In your application, you should call this before the application shuts down
	defer client.Close()

	// Manage devices for the application.
	devices, err := client.ManageDevices()
	if err != nil {
		log.WithError(err).Fatal("could not get device manager")
	}

	deviceList, err := devices.List(100, 0)
	if err != nil {
		log.WithError(err).Fatal("could not get devices")
	}
	log.Info("ethtrack: found devices")
	for _, device := range deviceList {
		fmt.Printf("- %s", device.DevID)
	}

	pubsub, err := client.PubSub()
	if err != nil {
		log.WithError(err).Fatal("ethtrack: could not get application pub/sub")
	}

	all := pubsub.AllDevices()
	defer all.Close()
	activations, err := all.SubscribeActivations()
	if err != nil {
		fmt.Println(err)
	}
	uplinks, err := all.SubscribeUplink()
	if err != nil {
		fmt.Println(err)
	}
	events, err := all.SubscribeEvents()
	if err != nil {
		fmt.Println(err)
	}

	for {
		select {
		case a := <-activations:
			fmt.Printf("Activation: %+v\n", a)
		case u := <-uplinks:
			fmt.Printf("Uplink: %+v\n", u)
		case e := <-events:
			fmt.Printf("Event: %+v\n", e)
		}
	}
}
```

**Comment by MarkStanley** [comment]
Many thanks @NeuralSpaz - works a treat.  Appreciate it is a workaround, but it is really helpful right now.

**Comment by htdvisser** [comment]
@MarkStanley @NeuralSpaz could you try with the following `go.mod` in your projects and let me know how that goes?

```
module yourmodule

replace github.com/brocaar/lorawan => github.com/ThethingsIndustries/legacy-lorawan-lib v0.0.0-20190212122748-b905ab327304

require github.com/TheThingsNetwork/go-app-sdk v0.0.0-20190212125043-3c550464b536
```

**Comment by NeuralSpaz** [comment]
@htdvisser 
It works with some minor changes to my code, but that is to be expected. 
Changes were to not use the my type alias not owned exported types of the sdk. ie sdk.Activation back to types.Activation etc.

go.mod:
```
module ttn-lora-test

replace github.com/brocaar/lorawan => github.com/ThethingsIndustries/legacy-lorawan-lib v0.0.0-20190212122748-b905ab327304

require (
	github.com/TheThingsNetwork/go-app-sdk v0.0.0-20190212125043-3c550464b536
	github.com/TheThingsNetwork/go-utils v0.0.0-20190212114733-b66819ba738f
	github.com/TheThingsNetwork/ttn/core/types v0.0.0-20190212124632-76cb46ffc7c8
	github.com/VividCortex/mysqlerr v0.0.0-20170204212430-6c6b55f8796f
	github.com/eclipse/paho.mqtt.golang v1.1.1
... etc
)
```

**Comment by htdvisser** [comment]
This issue should be solved now
